### ISSUE TITLE
Build is failing on GDAL configure

### ISSUE THREAD

**Issue by robe2** [postgis/postgis-build-env#19]
```
[0m[91mconfigure: error: cannot find required auxiliary files: config.rpath
[0mThe command '/bin/sh -c git clone --depth 1 --branch ${GDAL_BRANCH} https://github.com/OSGeo/gdal &&     cd gdal/gdal &&     ./autogen.sh && ./configure && make -j${BUILD_THREADS} && make install &&     cd /src && rm -rf gdal' returned a non-zero code: 1
Env Batch selected: weekly [{'name': 'latest', 'PG': 'master', 'GEOS': 'main', 'GDAL': 'master', 'PROJ': 'master', 'PG_CC': 'gcc'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': 'main', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'clang'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': '3.9', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'gcc'}]
Traceback (most recent call last):
  File "build.py", line 132, in <module>
    '.'
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '--build-arg', 'BUILD_DATE=20210913', '--build-arg', 'POSTGRES_BRANCH=master', '--build-arg', 'GEOS_BRANCH=main', '--build-arg', 'GDAL_BRANCH=master', '--build-arg', 'PROJ_BRANCH=master', '--build-arg', 'PG_CC=gcc', '-t', 'postgis/postgis-build-env:latest', '.']' returned non-zero exit status 1.
```

**Comment by robe2** [comment]
Okay I tried others and fails as well.

These look similar to the issues we were having in PostGIS before @Algunenano  made patches to our configure script.  I think why it started failing now is we are using debian:unstable-slim and looks like debian:unstable-slim upgraded their autoconf to 2.71.  I'm testing now with debian:stable-slim to see if it passes (I think that still has 2.69 or I hope so).  If so I'll try building GDAL with my new msys2 which has autoconf 2.71 and I should run into the same issues.

**Comment by robe2** [comment]
Okay looks like it's working with debian:stable-slim.  I'll revise the script after I have confirmed it's working and then also test on my local trying to build latest GDAL with autoconf.  I expect it to fail and then will try to patch.

**Comment by rouault** [comment]
> before @Algunenano made patches to our configure script

pointers ? if we can port that to GDAL too

**Comment by robe2** [comment]
@rouault   Take a look at https://github.com/postgis/postgis/commit/f6e37c3e70dca282d99829bba13137cb913f191a

**Comment by robe2** [comment]
I'm going to close this one out since GDAL has switched to CMake
